name: Label PR for Excluded Analysis

on:
  pull_request:
    types: [opened, edited]
env:
  EXCLUDED_LABEL: "Excluded Analysis"
  EXCLUDED_COMBINATIONS: "develop:master, develop:r3_2_feature, r2_develop:r3_2_feature, features/excluede_analtcs:develop"
  PR_TITLE: "${{ github.event.pull_request.title }}"
  BASE_BRANCH: "${{ github.event.pull_request.base.ref }}"
  HEAD_BRANCH: "${{ github.event.pull_request.head.ref }}"

jobs:
  label-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR Conditions
        id: check_conditions
        run: |
          # 除外ブランチの組み合わせを配列に設定
          IFS=', ' read -r -a COMBINATION_ARRAY <<< "${{ env.EXCLUDED_COMBINATIONS }}"
          
          # 条件1: ブランチの組み合わせをチェック
          for COMBINATION in "${COMBINATION_ARRAY[@]}"; do
            echo "COMBINATION: $COMBINATION"
            IFS=":" read -r SOURCE TARGET <<< "$COMBINATION"
            echo "ソース： $SOURCE ターゲット: $TARGET"
            if [[ "${{ env.HEAD_BRANCH }}" == "$SOURCE" && "${{ env.BASE_BRANCH }}" == "$TARGET" ]]; then
              echo "true" > condition_met
              break
            fi
          done

          # 条件2: タイトルに"本番リリース"が含まれているかチェック
          echo "タイトル：${{ env.PR_TITLE }}"
          if [[ "${{ env.PR_TITLE }}" == *"本番リリース"* ]]; then
            echo "true" > condition_met
          fi

          # ラベルを付与する必要があるかどうか
          if [[ -f condition_met ]]; then
            echo "::set-output name=label_needed::true"
          else
            echo "::set-output name=label_needed::false"
          fi

      - name: Add Label if Needed
        if: steps.check_conditions.outputs.label_needed == 'true'
        run: gh issue edit "$NUMBER" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: ${{ env.EXCLUDED_LABEL }}