name: ManualTrigger

on:
  workflow_dispatch:
    inputs:
      gitTag:
        description: 'git tag version (x.y.z)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          echo Hello, world!
          echo build num: $GITHUB_RUN_NUMBER
          echo branch name: ${GITHUB_REF##*/}
          echo GITHUB_REF: $GITHUB_REF
          echo "git tag version: ${{ github.event.inputs.gitTag }}"
      - name: check
        run: |
          echo "リリースブランチ整合性チェック"
          SELECT_BRANCH_NAME=${GITHUB_REF##refs/heads/}
          RELEASES_BRANCH_NAME=releases/${{ github.event.inputs.gitTag }}
          if [ "${SELECT_BRANCH_NAME}" != "${RELEASES_BRANCH_NAME}" ]; then
            echo "選択したブランチもしくは入力したタグが誤っています。"
            echo "選択したブランチ: ${SELECT_BRANCH_NAME}"
            echo "期待するブランチ: ${RELEASES_BRANCH_NAME}"
            exit 1
          fi
          
          git fetch --prune --unshallow --tags
          # git tag
          # TAG=${{ github.event.inputs.gitTag }}
          # echo ${TAG}
          # echo "git tag | grep -e ^${TAG}$"
          echo "Gitタグ存在チェック"
          # 存在しない場合は、GitHub ActionsはNGとして終了する
          git tag | grep -e ^${{ github.event.inputs.gitTag }}$
          
          echo OK
  output_confirm:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set IMAGE_TAG
        run: echo "IMAGE_TAG=${{ github.event.inputs.gitTag }}" >> $GITHUB_ENV
      - name: git branch name
        run: |
          git fetch --prune --unshallow --tags
          git checkout ${{ github.event.inputs.gitTag }}
          git branch --contains
          echo $IMAGE_TAG
