name: features test
on:
  repository_dispatch:
    types: [test]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: echo
        run: |
          echo "api test"
          echo GITHUB_REF: $GITHUB_REF