# This is a basic workflow to help you get started with Actions

name: sample_workflow_dispatch

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on: [ workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo Hello, world!
      - uses: actions/checkout@v2
      - name: git checkout tag
        run: |
          git fetch --prune --unshallow --tags
          git checkout ${TAG}
          git branch --contains
